/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedDashboardSubscriptionsIndexRouteImport } from './routes/_protected/dashboard/subscriptions/index'
import { Route as ProtectedDashboardSettingsIndexRouteImport } from './routes/_protected/dashboard/settings/index'
import { Route as ProtectedDashboardReviewsIndexRouteImport } from './routes/_protected/dashboard/reviews/index'
import { Route as ProtectedDashboardRepositoryIndexRouteImport } from './routes/_protected/dashboard/repository/index'
import { Route as ApiWebhooksGithubSplatRouteImport } from './routes/api/webhooks/github/$'

const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardSubscriptionsIndexRoute =
  ProtectedDashboardSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSettingsIndexRoute =
  ProtectedDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardReviewsIndexRoute =
  ProtectedDashboardReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardRepositoryIndexRoute =
  ProtectedDashboardRepositoryIndexRouteImport.update({
    id: '/repository/',
    path: '/repository/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ApiWebhooksGithubSplatRoute = ApiWebhooksGithubSplatRouteImport.update({
  id: '/api/webhooks/github/$',
  path: '/api/webhooks/github/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/api/inngest': typeof ApiInngestRoute
  '/auth/login': typeof AuthLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/api/webhooks/github/$': typeof ApiWebhooksGithubSplatRoute
  '/dashboard/repository/': typeof ProtectedDashboardRepositoryIndexRoute
  '/dashboard/reviews/': typeof ProtectedDashboardReviewsIndexRoute
  '/dashboard/settings/': typeof ProtectedDashboardSettingsIndexRoute
  '/dashboard/subscriptions/': typeof ProtectedDashboardSubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/api/inngest': typeof ApiInngestRoute
  '/auth/login': typeof AuthLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/api/webhooks/github/$': typeof ApiWebhooksGithubSplatRoute
  '/dashboard/repository': typeof ProtectedDashboardRepositoryIndexRoute
  '/dashboard/reviews': typeof ProtectedDashboardReviewsIndexRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsIndexRoute
  '/dashboard/subscriptions': typeof ProtectedDashboardSubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/api/inngest': typeof ApiInngestRoute
  '/auth/login': typeof AuthLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/api/webhooks/github/$': typeof ApiWebhooksGithubSplatRoute
  '/_protected/dashboard/repository/': typeof ProtectedDashboardRepositoryIndexRoute
  '/_protected/dashboard/reviews/': typeof ProtectedDashboardReviewsIndexRoute
  '/_protected/dashboard/settings/': typeof ProtectedDashboardSettingsIndexRoute
  '/_protected/dashboard/subscriptions/': typeof ProtectedDashboardSubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/how-it-works'
    | '/dashboard'
    | '/api/inngest'
    | '/auth/login'
    | '/api/auth/$'
    | '/dashboard/'
    | '/api/webhooks/github/$'
    | '/dashboard/repository/'
    | '/dashboard/reviews/'
    | '/dashboard/settings/'
    | '/dashboard/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/how-it-works'
    | '/api/inngest'
    | '/auth/login'
    | '/api/auth/$'
    | '/dashboard'
    | '/api/webhooks/github/$'
    | '/dashboard/repository'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/features'
    | '/how-it-works'
    | '/_protected/dashboard'
    | '/api/inngest'
    | '/auth/login'
    | '/api/auth/$'
    | '/_protected/dashboard/'
    | '/api/webhooks/github/$'
    | '/_protected/dashboard/repository/'
    | '/_protected/dashboard/reviews/'
    | '/_protected/dashboard/settings/'
    | '/_protected/dashboard/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ApiInngestRoute: typeof ApiInngestRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksGithubSplatRoute: typeof ApiWebhooksGithubSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/subscriptions/': {
      id: '/_protected/dashboard/subscriptions/'
      path: '/subscriptions'
      fullPath: '/dashboard/subscriptions/'
      preLoaderRoute: typeof ProtectedDashboardSubscriptionsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/settings/': {
      id: '/_protected/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof ProtectedDashboardSettingsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/reviews/': {
      id: '/_protected/dashboard/reviews/'
      path: '/reviews'
      fullPath: '/dashboard/reviews/'
      preLoaderRoute: typeof ProtectedDashboardReviewsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/repository/': {
      id: '/_protected/dashboard/repository/'
      path: '/repository'
      fullPath: '/dashboard/repository/'
      preLoaderRoute: typeof ProtectedDashboardRepositoryIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/api/webhooks/github/$': {
      id: '/api/webhooks/github/$'
      path: '/api/webhooks/github/$'
      fullPath: '/api/webhooks/github/$'
      preLoaderRoute: typeof ApiWebhooksGithubSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDashboardRepositoryIndexRoute: typeof ProtectedDashboardRepositoryIndexRoute
  ProtectedDashboardReviewsIndexRoute: typeof ProtectedDashboardReviewsIndexRoute
  ProtectedDashboardSettingsIndexRoute: typeof ProtectedDashboardSettingsIndexRoute
  ProtectedDashboardSubscriptionsIndexRoute: typeof ProtectedDashboardSubscriptionsIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedDashboardRepositoryIndexRoute:
    ProtectedDashboardRepositoryIndexRoute,
  ProtectedDashboardReviewsIndexRoute: ProtectedDashboardReviewsIndexRoute,
  ProtectedDashboardSettingsIndexRoute: ProtectedDashboardSettingsIndexRoute,
  ProtectedDashboardSubscriptionsIndexRoute:
    ProtectedDashboardSubscriptionsIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  ApiInngestRoute: ApiInngestRoute,
  AuthLoginRoute: AuthLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksGithubSplatRoute: ApiWebhooksGithubSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
